export const MAX_TOKENS = 9;
export const TARGET_AGENTS = 15;

// A robust list of distinct French nouns suited for Codenames
export const FRENCH_WORDS = [
  "AVION", "NUAGE", "ROBOT", "LUNE", "PONT", "PYRAMIDE", "BANANE", "DOCTEUR", "ARAIGNÉE", "SOLDAT",
  "PIANO", "FEU", "GLACE", "LIVRE", "ROI", "REINE", "SOURIS", "CHAISE", "LIT", "MONTRE",
  "CŒUR", "OR", "ARGENT", "POISON", "FORÊT", "OCÉAN", "TRAIN", "BOMBE", "AMOUR", "GUERRE",
  "CHIEN", "CHAT", "LION", "TIGRE", "OURS", "AIGLE", "REQUIN", "BALEINE", "DINOSAURE", "FANTÔME",
  "VAMPIRE", "SORCIÈRE", "ZOMBIE", "ALIEN", "ESPACE", "PLANÈTE", "ÉTOILE", "SOLEIL", "PLUIE", "NEIGE",
  "VENT", "TEMPÊTE", "ÉCLAIR", "TONNERRE", "ARC-EN-CIEL", "FLEUR", "ARBRE", "FRUIT", "LÉGUME", "VIANDE",
  "PAIN", "VIN", "BIÈRE", "EAU", "LAIT", "CAFÉ", "THÉ", "CHOCOLAT", "GÂTEAU", "GLACE",
  "MAISON", "ÉCOLE", "HÔPITAL", "PRISON", "BANQUE", "POSTE", "MAGASIN", "CINÉMA", "THÉÂTRE", "STADE",
  "PISCINE", "PLAGE", "MONTAGNE", "DÉSERT", "JUNGLE", "RIVIÈRE", "LAC", "MER", "ÎLE", "GROTTE",
  "VOLCAN", "TREMBLEMENT", "TORNADE", "INCENDIE", "EXPLOSION", "ACCIDENT", "MEURTRE", "VOL", "ARME", "FUSIL",
  "ÉPÉE", "BOUCLIER", "CASQUE", "ARMURE", "CHEVALIER", "PRINCESSE", "DRAGON", "LICORNE", "FÉE", "LUTIN",
  "GÉANT", "NAIN", "ELFE", "OGRE", "TROLL", "MONSTRE", "MOMIE", "SQUELETTE", "CRÂNE", "OS"
];
